### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by jtapia** [mrkamel/spreadshirt_client#4]
Could you change the version to include the new changes, please? because the last version is the 0.0.7 but it doesn't include your new changes

For example https://github.com/mrkamel/spreadshirt_client/commit/7fbb979cb8061d02b5f0ff7f550030200913892f#diff-491ada7ffb3059e9cc1ae5ed3d19b3a7R24

Thanks

**Comment by mrkamel** [comment]
done, thx
